export const APP_ROUTES = {
    DASHBOARD: '/',
    SIEBAR: '/sidebar',
    MENUBAR: '/menu',
    LOGIN: '/login',
    REGISTER: '/register',
    DOCTORS: '/doctors',
    DOCTOR_BIO: '/doctors/:doctid',
    HOSPITAL: '/hospital',
    MEDICINE: '/medicine',
    MEDICINE_ALL_PRODUCTS: "/allmedicines",
    DIAGNOSIS: '/diagnosis',
    PHR: '/phr',
    AMBULANCE: '/ambulance',
    NOTIFICATION: '/notification',
    CART_ORDER_SUCESS: '/order-sucess',
    FORGET_PASSWORD: '/patientforgetpassword',
    SEE_ALL_COMMON_LABTEST: '/common-lab-test',
    // CART: '/cart',
    PROFILE: '/profiles',
    MOBILE_SEARCH:'/m_search',
    MEMBERSHIP: '/membership',
    NOT_FOUND: '/not-found',
    PAYMENT: '/payment',
    DOCTOR_SEARCH: '/doctor-search',
    FAMILY_SEARCH: '/family-search',
    SPECIALITIES_SEARCH: '/Specialities-search',
    COMMON_HEALTHS_SEARCH: '/common-healthes-search',
    APPOINMENT_CONFIRM: '/confirm_appointment',
    POST_CONSULTATION: '/post_consultation',
    PRESCRIPTION: '/prescription',
    MEDICINE_COMPARISON: '/medicine_comparison',
    MEDICINE_CART: '/cart',
    MEDICINE_PAYMENT: '/medicine_payment',
    ORDER_DETAILS: '/OrderDetails',
    HOSPITAL_DETAILS: '/hospitaldetails/:hospitalid',
    // SINGLE_OCCUPANCY: '/singleoccupancy',
    RECOMMENDED_SPECIALITY: '/recommondedspeciality',
    DOWNLOAD: '/download',
    DIAGNOSTICS_HEALTHPACKAGE: '/diagnosticsHealthpackage',
    COMPLETEBLOOD_COUNTTEST: '/testDetails',
    LABTEST_SEARCH: '/labtestsearch',
    LALPATH_LAB: '/labDetails',
    ALL_LABTEST: '/alllabtest',
    ALL_RADIOLOGY: '/allradiology',
    COMINGSOON: '/comingSoon',
    DIAGNOSTICS_LANDINGPAGE: '/diagnosticslandingpage',
    DIAGNOSTICS_TESTDETAILS: '/diagnosticstestdetails',
    CART_PAYMENT: '/cartpayment',
    CART_SUCCESSFUL: '/cartappointment',
    MEDICINE_SEARCHRESULT: '/medicineserachresult',
    MEDICINE_CATEGORY: '/medicinecategory',
    MEDICINE_PRODUCT: '/medicineproduct',
    PHARMACY_LIST: '/pharmacylist',
    PHARMACY_CATEGOTY: '/pharmacycategory',
    // MEDICINE_CART: '/medicinecart',
    MEDICINE_ORDERPLACE: '/medicine_orderplace',
    CART_SUMMARY: '/cartsummary',
    PRESCRIPTION_MEDICINE: '/prescriptionmedicine',
    UPLOADED_PRESCRIPTION: '/prescriptionuploaded',
    VIDEO_CALL: '/videocall',
    SPECIALITY_DOCTORS: '/speciality/:spectdoct',
    SYMPTOMS_DOCTORS: '/symptoms/:spectdoct',
    HOSPITAL_SEARCH: '/hospitalsearch',
    HOSPITAL_ENQUIRY: '/hospitalenquiry',
    ALL_SEARCH: '/all',
    RECENT_MED: '/cart-history',
    HOSPITAL_BIODETAILS:"/HospitalBiodetails/:hospitalid",
    MEDICINEDELIVERYORDERDETAILS: "/medicinedeliveryorderdetails",
    PACKAGEORDERDETAILS: "/packageorderdetails",
    PRIVACY_POLICY: "/privacy-policy",
    ABOUTUS : '/aboutus',
    OUR_TEAM : '/our-team',
    TERMS_AND_CONDITION: "/terms-and-condition",
    REFUND_POLICY: "/refund-policy",
    COMPARE_PRESCRIPTIONS: "/compare-prescription",

    CONTACTWITHUS : '/contact-with-us',
    MEDIA: '/Media'
}



