export const USERPROFILE_ROUTES = {
    SIDEBAR: '/sidebar',
    PROFILE: '/profile',
    MYDETAILS: '/profile/mydetails',
    MANAGEPROFILE: '/profile/manageprofile',
    MYREPORTS: '/profile/myreports',
    MYPRISCRIPTION:'/profile/mypriscription',
    MYMEDICALHISTORY : '/profile/mymedicalhistory',
    MYINSURANCE: '/profile/insurance',
    MYORDERS: '/profile/orders',
    MYAPPOINTMENTS: '/profile/appointments',
    MYPAYMENTS: '/profile/payments',
    MYWALLET:'/profile/wallet',
    MYADDRESSBOOK: '/profile/addressbook',
    MYCHANGEPASSWORD: '/profile/changepassword',
    MYFEEDBACK: '/profile/feedback',
    MYHELPSUPPORT: '/support',
    MYVITALS: '/profile/myvitals',
    MEDICATIONS: '/profile/myvitals/medications',
    INSURANCE: '/profile/myvitals/insurance',
    HEALTHRESTRICTIONS: '/profile/myvitals/healthrestrictions',
    ADDDMEMBERS: '/profile/addmembers',
    ADDADDRESS: '/profile/addaddress',
    VIEWAPPOINTMENT: '/profile/viewappointments',
   
    REPORTS_VITALS: '/profile/myvitals/reportsvital',
    ADD_ALLERGY: '/profile/myvitals/addallergy',
    ADD_MEDICAL: '/profile/myvitals/addmedical',
    MEDICAL_CONDITION: '/profile/myvitals/medicalcondition',
    MEDICAL_PRESCRIPTION: '/profile/myvitals/medicineprescription',

    APPOINTMENTDETAILS: '/appointmentdetails',
    SEEALL_ALLERGY: '/seeallallergy',
    _ADD_ALLERGY: '/addallergy',
    SEEALL_HEALTHRESTRICTION: '/seeallhealthrestriction',
    SEEALL_MEDICATION: '/seeallmedications',
    SEEALLMEDICATION: '/seeallmedication',
    SEEALL_MEDICALHISTORY: '/seeallmedicalhistory',
    ADDMEDICALHISTORY : '/Addmedicalhistory',
    SEEALLMEDICALHISTORY : '/seeallmedicalhistory',
    SEEALLSOCIALHISTORY: '/seeallsocialhistory',
    SEEALLFAMILYHISTORY: '/seeallfamilyhistory',
    MYLABREPORT: '/profile/labreport',
    MYHELTH_MEDICATIONS: '',
    SEE_MYHELTH_MEDICATIONS : '',
    
    //Notification 
    MYNOTIFICATION : '/profile/notifications/:type',
    MYREQUESTS: '/profile/myrequests',
    ADDADDRESS : '/profile/address',

    //My Orders 
    PATIENTMEDICINEORDERS: '/profile/mediceineorders',
    PATIENTMEPACKAGEORDERS: '/profile/packagesineorders',
    MY_ORDERS : '/profile/laborders',

    SEEALLSURGICALHISTORY: '/seeallsurgicalhistory',
    //SEEALLSURGICALHISTORY: '/seeallsocialhistory',

    
}