export const DASH = {
    REQUEST_LOGINCHEUSER: "REQUEST_LOGINCHEUSER",
    SUCCESS_LOGINCHEUSER: "SUCCESS_LOGINCHEUSER",
    FAILED_LOGINCHEUSER: "FAILED_LOGINCHEUSER",

    REQUEST_UPCOMINGCONSULTATION: "REQUEST_UPCOMINGCONSULTATION",
    SUCCESS_UPCOMINGCONSULTATION: "SUCCESS_UPCOMINGCONSULTATION",
    FAILED_UPCOMINGCONSULTATION: "FAILED_UPCOMINGCONSULTATION",

    REQUEST_UPCOMINGLABAPPOINTMENTS: "REQUEST_UPCOMINGLABAPPOINTMENTS",
    SUCCESS_UPCOMINGLABAPPOINTMENTS: "SUCCESS_UPCOMINGLABAPPOINTMENTS",
    FAILED_UPCOMINGLABAPPOINTMENTS: "FAILED_UPCOMINGLABAPPOINTMENTS",

    REQUEST_HOSPITALENQUIRYLIST: "REQUEST_HOSPITALENQUIRYLIST",
    SUCCESS_HOSPITALENQUIRYLIST: "SUCCESS_HOSPITALENQUIRYLIST",
    FAILED_HOSPITALENQUIRYLIST: "FAILED_HOSPITALENQUIRYLIST",

    REQUEST_CHEMEDICINEDELIVERYLIST: "REQUEST_CHEMEDICINEDELIVERYLIST",
    SUCCESS_CHEMEDICINEDELIVERYLIST: "SUCCESS_CHEMEDICINEDELIVERYLIST",
    FAILED_CHEMEDICINEDELIVERYLIST: "FAILED_CHEMEDICINEDELIVERYLIST",
    
}